# -*- coding: utf-8 -*-
"""ood_e-itim.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/halilcnr/bc18c8b046e34044961a8303922a5c80/ood_e-itim.ipynb

Ekran kartının modelini gösteriyor
"""

!nvidia-smi

"""sistem işlemleri kütüphanesini içe aktarıyoruz ve home diye bir değişken belirliyoruz.
Not: Data seti yükledikten sonra çalışma zamanını sıfırladığımızda bu satırı yeniden çalıştırmamız gerekiyor
"""

import os
HOME = os.getcwd()
print(HOME)

"""YOLOv8 indirme import etme satırı. En son sürüm neyse onu indirir."""

!pip install ultralytics

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

"""YOLO'yu içe aktarma."""

from ultralytics import YOLO

from IPython.display import display, Image

"""Roboflowdan aldığın dataset kodunu buraya yapıştırın.
not: Kendi veri setinizi kullanacaksanız bu satırı çalıştırmayın. Colaba sürükleyin.
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="egchH4Y73wxoB1ArLk4w")
project = rf.workspace("sreyoshi-mitra").project("fire_detection-d5jqa")
dataset = project.version(3).download("yolov8")

"""Epoch ve image size'yi seçilecek.
data sete sağ tıklayıp dosya yolunu alıp dataset.location yerine yapıştır.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolov8s.pt data=/content/Fire_Detection-3/data.yaml epochs=25 imgsz=640 plots=True

"""Sonuçlar train klasörü içinde oluyor neyi ekrana yazdırmak istiyorsanız hangi train klasörü içinde ise ona girin yolunu kopyalayın buraya yapıştırın."""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
from IPython.display import Image

Image(filename=f'{HOME}/runs/detect/train/confusion_matrix.png', width=600)

"""Hangi"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=predict model=/content/runs/detect/train/weights/last.pt conf=0.45 source=/content/tekneli.mp4 save=True